### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by bec-smith** [ErikBjare/N-Back#1]
Hello, I installed Pygame and am unsure how to run this program.
Here is my terminal: 

**_Becs-Macintosh:N-Back-master BNS$ python3 __init__.py
Traceback (most recent call last):
  File "__init__.py", line 7, in <module>
    import main
  File "/Users/BNS/Downloads/N-Back-master/main.py", line 19, in <module>
    from nBack import NBack
  File "/Users/BNS/Downloads/N-Back-master/nBack.py", line 15, in <module>
    import UI
  File "/Users/BNS/Downloads/N-Back-master/UI/__init__.py", line 10, in <module>
    import activities
ModuleNotFoundError: No module named 'activities'_**

**Comment by ErikBjare** [comment]
Sorry for this issue, I wrote this a long time ago when I was still a
complete noob at Python (and programming at large).

I can help you get it running though if you are still interested, but I
want to know why you're interested in it. I can point you to other, better
developed, alternatives if you'd like.

**Comment by ErikBjare** [comment]
Solution: Run the program with `python .`, not `python main.py`.

**Comment by ErikBjare** [comment]
My bad, `python main.py` is correct. I fixed the issue in a new commit.
